import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ResidentFlow",
  description: "Generated by create next app",
};

import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { auth } from "@clerk/nextjs/server";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Link from "next/link";
import { UserSyncWrapper } from "@/components/UserSyncWrapper";


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = await auth();
  console.log("Layout: userId =", userId);

  let dbUser = null;
  if (userId) {
    dbUser = await db.query.users.findFirst({
      where: eq(users.clerkId, userId),
    });
    console.log("Layout: dbUser =", dbUser);
  }

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <UserSyncWrapper>
            <header className="border-b">
              <div className="container mx-auto flex h-16 items-center justify-between">
                <Link href="/" className="font-bold">
                  ResidentFlow
                </Link>

                <div className="flex items-center gap-4">
                  {(dbUser?.role === "admin" || dbUser?.role === "super_admin") && (
                    <Link href="/admin">
                      <Button variant="ghost">Admin Tools</Button>
                    </Link>
                  )}
                  <SignedOut>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="outline">Sign In</Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent>
                        <DropdownMenuItem asChild>
                          <Link href="/sign-in">Sign In</Link>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </SignedOut>
                  <SignedIn>
                    <UserButton afterSignOutUrl="/" />
                  </SignedIn>
                </div>
              </div>
            </header>
            <main className="container mx-auto py-8">{children}</main>
          </UserSyncWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
